apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.api.port }}
